### ISSUE TITLE
Question about cost-modifier choices

### ISSUE THREAD

**Issue by zyrgit** [argos-research/sumo#3]
Hi, can you tell me the difference between the cost-modifier  choices: ('grohnde', 'isar', 'None')?

If it is None, then there is no change of edge weights, and iterations of routing will not consider traffic load information, right?

Thanks!

**Comment by irgendwie** [comment]
Hello! Sorry, but we're not affiliated to the SUMO project and this is merely an old fork of SUMO in order to extend the TraCI-API.
I'd suggest you ask your question in the official repository: https://github.com/eclipse/sumo

**Comment by zyrgit** [comment]
OK thanks for pointing out!
