### ISSUE TITLE
traci.simulation.getDepartedNumber() does not return the right number 

### ISSUE THREAD

**Issue by xiahaochong** [argos-research/sumo#4]
Hello, I used traci.simulation.getDepartedNumber() to count the number of cars inserted in my simulation. However, I found out that the number it returns only equals to almost half(not exactly half) of the cars that truly inserted in my simulation. I am an amateur in coding and I don't know how to look into your code to find the code that does the calculation for traci.simulation.getDepartedNumber(). Can you check this function? Thank you!

**Comment by irgendwie** [comment]
Hello! Sorry, but we're not affiliated to the SUMO project and this is merely an old fork of SUMO in order to extend the TraCI-API.
I'd suggest you ask your question in the official repository: https://github.com/eclipse/sumo
